app/modules/depositor_login/depositor_login/__init__.py
from .ext import LoginApp
__all__ = ('LoginApp')

app/modules/depositor_login/depositor_login/views.py
import random
import string
import os
from flask import Flask, render_template, redirect, url_for, request, flash, session ,current_app, jsonify, Blueprint
from flask_login import login_user, current_user, logout_user
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField ,PasswordField
from .config import MOCK_SHIB_DATA
from depositor_models.user import User, User_manager
from depositor_models.affiliation_id import Affiliation_Id, Affiliation_Id_manager

blueprint = Blueprint(
    "login",
    __name__,
    url_prefix="/",
    template_folder="templates",
    static_folder="static")

class LoginForm(FlaskForm):
    email = StringField('メールアドレス')
    password = PasswordField('パスワード')
    submit = SubmitField('ログイン')

@blueprint.route("", methods=['GET'])
def top():
    return index_login()

@blueprint.route("/login", methods=['GET'])
def index_login():
    if not current_user.is_anonymous:
        return redirect(url_for('item_register.index_item'))
    csrf_random = generate_random_str(length=64)
    session['csrf_random'] = csrf_random
    login_user_form = LoginForm()
    
    return render_template("login/login_index.html", login_user_form = login_user_form)

@blueprint.route("/login", methods=['POST'])
def login():
    mock_password = os.environ.get("MOCK_PASSWORD")
    form=LoginForm()
    if form.validate_on_submit():
        # shibbolethで返ってくる値を固定値とする。パスワードは環境変数で固定
        if form.password.data == mock_password:
            shib_data = MOCK_SHIB_DATA.get(form.email.data)
            if shib_data :
                affiliation_idp_url = shib_data.get("affiliation_idp_url",None)
                affiliation_id = Affiliation_Id_manager.get_affiliation_id_by_idp_url(affiliation_idp_url)
                if not affiliation_id:
                    affiliation_name = shib_data.get("OrganizationName",None)
                    aff_id = Affiliation_Id(affiliation_idp_url=affiliation_idp_url, affiliation_name=affiliation_name)
                    affiliation_id = Affiliation_Id_manager.create_affiliation_id(aff_id)
                affiliation_id_id = affiliation_id.id
                user_id = shib_data.get("eduPersonPrincipalName",None)
                user=User_manager.get_user_by_user_id(user_id)
                if not user :
                    user_orcid = shib_data.get("eduPersonOrcid",None)
                    role = shib_data.get("wekoSocietyAffiliation", None)
                    user = User(
                        user_id = user_id,
                        affiliation_id = affiliation_id_id,
                        user_orcid = user_orcid,
                        role = role
                    )
                    User_manager.create_user(user)
                login_user(user)
                return redirect(url_for("item_register.index_item"))
    flash("Missing SHIB_ATTRs!", category='error')
    return index_login()


@blueprint.route("/logout", methods=['GET'])
def logout():
    logout_user()
    return redirect(url_for('login.top'))


def generate_random_str(length=128):
    """Generate secret key."""
    rng = random.SystemRandom()

    return ''.join(
        rng.choice(string.ascii_letters + string.digits)
        for _ in range(0, length)
    )

app/modules/depositor_login/depositor_login/templates/login/_macros.html
{% macro render_field(field, icon="", autofocus=False, errormsg=True, size="form-group-lg") %}
  <div class="form-group {{size}}{% if icon %} has-feedback{% endif %}{% if field.errors %} has-error{% endif %}">
    {%- set extras = dict(autofocus="") if autofocus else dict() %}
    {{field(class_="form-control", placeholder=(field.label.text | string), **extras)}}
    {%- if icon %}
    <i class="{{icon}} form-control-feedback" aria-hidden="true" ></i>
    {%- endif%}
  </div>
  {%- if field.errors and errormsg %}
  <div class="text-danger text-left" role="alert">
    {%- for error in field.errors %}
    <p>{{error}}</p>
    {%- endfor %}
  </div>
  {%- endif %}
{% endmacro %}

{% macro form_errors(form) %}
  {%- if form.errors %}
  <div class="alert alert-danger alert-dismissible text-left" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      {%- for key,err_obj in form.errors.items() recursive%}
          {%  if err_obj is mapping %}
              {{  loop(err_obj.items()) }}
          {% else %}
              {% for single_message in err_obj %}
                <p>{{ single_message }}</p>
              {% endfor %}
          {% endif %}
      {%- endfor %}
  </div>
  {%- endif %}
{% endmacro %}

app/modules/depositor_login/depositor_login/templates/login/login_index.html
{#
# This file is part of WEKO3.
# Copyright (C) 2017 National Institute of Informatics.
#
# WEKO3 is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# WEKO3 is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WEKO3; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    {% block page_header %}
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
        </div>
      </div>
    </div>
    {% endblock page_header%}
  </head>
  {%- block css %}
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css";; rel="stylesheet">
  <link href={{url_for('static', filename='css/login/style.css')}} rel="stylesheet">
  {%- endblock css %}
  <div class="container">
    <body class="cover-page">
    {% from "login/_macros.html" import render_field, form_errors %}
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
        <div class="panel-body">
            {%- block form_header %}
            <h3 class="text-center panel-free-title">{{('Log in to account') }}</h3>
            {%- endblock form_header %}
            {%- block form_outer %}
            {%- with form = login_user_form %}
            <form action="{{ url_for('login.login') }}" method="POST" name="login_user_form">
            {{form.hidden_tag()}}
            {{form_errors(form)}}
            {{ render_field(form.email, icon="fa fa-user", autofocus=True, errormsg=False) }}
            {{ render_field(form.password, icon="fa fa-lock", errormsg=False) }}
            <button type="submit" class="btn btn-default btn-lg btn-block">
                <i class="fa fa-sign-in"></i> Shibboleth Login</button>
            {%- endwith %}
            {%- endblock form_outer %}
        </div>
        {%- block registerable %}

        {%- endblock %}
        </div>
        {%- block recoverable %}
        {%- endblock %}
    </div>
  </div>
</body>
</html>