app/modules/depositor_item_register/depositor_item_register/__init__.py
from .ext import ItemRegisterApp
__all__ = ('ItemRegisterApp')

app/modules/depositor_item_register/depositor_item_register/views.py
import base64
import zipfile
import io
import os
import shutil
import time
import uuid
import requests
import xml.etree.ElementTree as ET
from flask import Flask, render_template, redirect, url_for, request, flash, session ,current_app, jsonify, Blueprint
from flask_login import login_user, current_user, logout_user
from flask_wtf import FlaskForm
from grobid_client.grobid_client import GrobidClient, ServerUnavailableException
from depositor_models.affiliation_repository import Affiliation_Repository_manager
from .utils import dicttoxmlforsword # zip_folder

blueprint = Blueprint(
    "item_register",
    __name__,
    url_prefix="/item_register",
    template_folder="templates",
    static_folder="static")

@blueprint.route("/", methods=['GET'])
def index_item():
    if current_user.is_anonymous:
        return redirect(url_for('login.index_login'))
    form = FlaskForm(request.form)
    return render_template("item_register/item_index.html", form = form)


@blueprint.route("/register", methods=['POST'])
def register():
    # まだ、リクエストする方ができていないのでモック
    # 想定としては入力されたアイテムのメタデータ項目がrequestで投げられる。

    """
    post_dataの例:
    {"item_metadata;{}, "contentfiles": [{"name":"file.png", "base64":"aaaaa"}, "thumbneil":[{"name":"thumb.png", "base64":"bbbb"}] ]}
    """
    if current_user.is_anonymous:
        return redirect(url_for('login.index_login'))
    tmp_file_path = os.environ.get("TMPORARY_FILE_PATH")
    
    post_data = request.get_json()
    
    tmp_zip_name = str(uuid.uuid4())+".zip"

    # app/tmpディレクトリがないなら生成
    if not(os.path.exists(tmp_file_path)):
        os.mkdir(tmp_file_path)
    with zipfile.ZipFile(tmp_file_path+tmp_zip_name, mode="w") as zipf:
        # xml書き出し
        xml_string = dicttoxmlforsword("jpcoar2.0", post_data.get("item_metadata"))
        zipf.writestr("data/metadata.xml", xml_string)
        
        # コンテンツファイル書き込み
        for file in post_data.get("contentfiles"):
            binary_data = base64.b64decode(file.get("base64", ""))
            zipf.writestr("data/contentfiles/"+file.get("name",""), binary_data)
            
        # サムネイル書き込み
        for file in post_data.get("thumbnail"):
            binary_data = base64.b64decode(file.get("base64", ""))
            zipf.writestr("data/thumbnail/"+file.get("name",""), binary_data)
            
    # current_userよりaffiliation_idをとってaffiliaiton_repositoryテーブルからリポジトリURLをとる処理
    current_affiliation_id = current_user.affiliation_id
    aff_repository = Affiliation_Repository_manager.get_aff_repository_by_affiliation_id(current_affiliation_id)
    #　設定されている場合
    if aff_repository and not(aff_repository.repository_url=="" or aff_repository.access_token==""):
        repository_url=aff_repository.repository_url
        access_token=aff_repository.access_token
    else:
        aff_repository = Affiliation_Repository_manager.get_aff_repository_by_affiliation_name("default")
        repository_url=aff_repository.repository_url
        access_token=aff_repository.access_token
    
    sword_api_url = repository_url+"/sword/service-document"
    
    # 送信するデータ（辞書形式）
    data = {
        'file': '@'+tmp_zip_name+";type=application/zip"
    }

    # ヘッダーを定義
    headers = {
        'Authorization': 'Bearer '+access_token,
        'Content-Disposition': 'attachment; filename='+tmp_zip_name,
        "Packaging":"http://purl.org/net/sword/3.0/package/SimpleZip",
    }

    # 送信するファイル
    files = {'file': open(tmp_file_path+tmp_zip_name, 'rb')}  # ファイルのパスを指定してファイルを開く

    # POSTリクエストを送信
    # 該当リポジトリのswordapiにzipを投げる処理
    try:
        # current_app.logger.info(sword_api_url)
        # current_app.logger.info(data)
        # current_app.logger.info(headers)
        # current_app.logger.info(files)
        response = requests.post(url=sword_api_url, data=data, headers=headers, files=files, verify=False)
        if response.status_code == 404:
            return response.text, 404
        return jsonify(response.json()), response.status_code
    except requests.exceptions.RequestException as ex:
        current_app.logger.info(str(ex))
        return jsonify({"error":str(ex)}), 504
    except Exception as ex:
        current_app.logger.info(str(ex))
        return jsonify({"error":str(ex)}), 500
    finally:
        current_app.logger.info("一時zipファイル削除:"+tmp_zip_name)
        os.remove(tmp_file_path+tmp_zip_name)

@blueprint.route("/pdf_reader", methods=['POST'])
def pdf_reader():
    tmp_file_path = os.environ.get("TMPORARY_FILE_PATH")
    XMLNS="{http://www.tei-c.org/ns/1.0}"
    
    def read_title(data, root):
        for child in root:
            if child.tag.endswith("titleStmt"):
                data["title"] = child.find(f"{XMLNS}title").text
            else:
                read_title(data, child)
        return
    
    def read_date(data, root):
        for child in root:
            if child.tag.endswith("publicationStmt"):
                data["date"] = {}
                data["date"]["type"] = "Available"
                data["date"]["value"] = child.find(f"{XMLNS}date").attrib["when"]
            else:
                read_date(data, child)
        return
    
    def read_lang(data, root):
        for child in root:
            if child.tag.endswith("text"):
                for key, value in child.attrib.items():
                    if key.endswith("lang"):
                        data["lang"] = value
                        break
            else:
                read_lang(data, child)
        return
      
    def read_publisher(data, root):
        for child in root:
            if child.tag.endswith("publicationStmt"):
                data["publisher"] = child.find(f"{XMLNS}publisher").text
            else:
                read_publisher(data, child)
        return
      
    def read_author(data, root):
        for child in root:
            if child.tag.endswith("author"):
                name = child.find(f"{XMLNS}persName")
                if name:
                    author_data = {
                        "familyName":name.find(f"{XMLNS}surname").text,
                        "givenName":name.find(f"{XMLNS}forename").text
                    }
                    author_data["creatorName"] = author_data["familyName"] + " " + author_data["givenName"]
                    data["author"].append(author_data)
            else:
                read_author(data, child)
        return
    print("pdf read")
    if current_user.is_anonymous:
        return redirect(url_for('login.index_login'))
    current_app.logger.info(current_user.affiliation_id)
    # get and save PDF
    try:
        post_data = request.get_json()
        file_uuid = str(uuid.uuid4())
        file_name = None
        file_path = os.path.join(tmp_file_path, file_uuid)
        output_path = os.path.join(file_path, "output")
        
        # seetup PDF from json
        if not(os.path.exists(tmp_file_path)):
            os.mkdir(tmp_file_path)
        os.mkdir(file_path)
        with zipfile.ZipFile(os.path.join(file_path, "contents.zip"), mode="w") as zipf:
            for file in post_data.get("contentfiles"):
                if file.get("name","").endswith(".pdf"):
                    file_name = file.get("name","").replace(".pdf", ".grobid.tei.xml")
                    binary_data = base64.b64decode(file.get("base64", ""))
                    zipf.writestr(f"{file.get("name","")}", binary_data)
                    break
        with zipfile.ZipFile(os.path.join(file_path, "contents.zip")) as zf:
            zf.extractall(f"{file_path}/data")
            
        # PDF to XML by Grobid
        client = GrobidClient(config_path="./app/config.json")
        client.process("processHeaderDocument", file_path, output=output_path, consolidate_citations=True, tei_coordinates=True, force=True)
        
        # read XML
        tree = ET.parse(f"{output_path}/data/{file_name}")
        root = tree.getroot()
        data = {}
        data["author"] = []
        read_title(data, root)
        read_lang(data, root)
        read_date(data, root)
        read_publisher(data, root)
        read_author(data, root)
        print(data)
        
        return jsonify(data), 200
    except OSError as ex:
        current_app.logger.info(str(ex))
        return jsonify({"error":"PDFが適切ではない、またはPDFファイルが存在しない可能性があります。"}), 500
    except ServerUnavailableException as ex:
        current_app.logger.info(str(ex))
        return jsonify({"error":"PDF情報抽出機能との接続ができません。"}), 500
    except Exception as ex:
        current_app.logger.info(str(ex))
        return jsonify({"error":str(ex)}), 500
    finally:
        # remove tmp file
        shutil.rmtree(file_path)

app/modules/depositor_item_register/depositor_item_register/templates/item_register/_macros.html
{% macro tabs_selector(tab_value='top') %}
{%- if current_user.role == "管理者" %}
<li role="presentation" {% if tab_value=='add' %}class="active"{% endif %}><a href="{{url_for('admin_setting.add_affili')}}">{{ ('登録先追加') }}</a></li>
{%- endif %}
{%- if current_user.role == "管理者" or current_user.role == "図書館員" %}
<li role="presentation" {% if tab_value=='setting' %}class="active"{% endif %}><a href="{{url_for('admin_setting.index_affili')}}">{{ ('登録先設定') }}</a></li>
{%- endif %}
<li role="presentation" {% if tab_value=='item_index' %}class="active"{% endif %}><a href="{{ url_for('item_register.index_item') }}">{{ ('アイテム登録') }}</a></li>
{% endmacro %}

app/modules/depositor_item_register/depositor_item_register/templates/item_register/item_index.html
<!DOCTYPE html>
<!-- saved from url=(0041)http://localhost:5001/affiliation_setting -->
<html lang="ja" dir="ltr">

<body itemscope="" itemtype="http://schema.org/WebPage" data-spy="scroll" data-target=".scrollspy-target">
  {{ form.csrf_token }}
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
  <!-- <script src="https://unpkg.com/react@18/umd/react.production.min.js" type="text/babel"></script> -->
  <!--<script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js" type="text/babel"></script>-->
  <script src="{{ url_for('static', filename='js/jquery/jquery-3.7.1.js') }}"></script>
  <!-- <script src="{{ url_for('static', filename='js/react/react-datepicker-min.js') }}" type="text/babel" data-type="module"></script> -->
  <!-- <script async src="https://ga.jspm.io/npm:es-module-shims@1.7.0/dist/es-module-shims.js"></script> -->
  <!-- "/static/js/react/react.production.min.js" -->
  <script type="importmap">
    {
      "imports": {
        "react": "https://esm.sh/react?dev",
        "react-dom":"https://esm.sh/react-dom?dev",
        "react-dom/client": "https://esm.sh/react-dom/client?dev",
        "react-modal":"https://esm.sh/react-modal?dev"
      }
    }
  </script>
  <script src="static/js/app.js" data-type="module" type="text/babel"></script>
  <!-- <script src="{{ url_for('static', filename='js/app.js') }}" type="text/babel" data-type="module"></script> -->

  <link href={{url_for('static', filename='css/deposit.css' )}} rel="stylesheet">
  <link href={{url_for('static', filename='css/theme.css' )}} rel="stylesheet">
  <link href={{url_for('static', filename='css/styles.css' )}} rel="stylesheet">
  <link href={{url_for('static', filename='css/buttons.css' )}} rel="stylesheet">
  <link href={{url_for('static', filename='css/widget.css' )}} rel="stylesheet">
  <link href={{url_for('static', filename='css/admin.css' )}} rel="stylesheet">
  <!--<link href={{url_for('static', filename='css/item_register.css' )}} rel="stylesheet">-->

  <!--[if lt IE 8]>
      <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
  <div id="page_body" class="grid-stack" style="display: block;">
    <!-- header start-->
    {% include "header.html" %}
    <!-- header end -->
    <div id="main_contents">
      <div class="container-fluid container-fluid2">
        <div class="row row-4">
          <div class="col-sm-12 col-md-12 col-md-12">
            <div class="panel panel-default" id="panel-main-content">
              <div class="panel-heading no-padding-side" id="panel-heading-main-contents">
                <div class="pull-right">
                </div>
                <strong>
                  <p id="title-main-content">Overlay</p>
                </strong>
              </div>
              <div class="panel-body panel-body2" id="background-color-main-content">
                <ul class="nav nav-tabs">
                  {%- block page_body_tabs %}
                  {% from "item_register/_macros.html" import tabs_selector with context %}
                  {{ tabs_selector('item_index') }}
                  {%- endblock page_body_tabs %}
                  <div class="row row-4" style="height: 100%">
                    <div class="col-sm-12 col-md-12" style="height: 100%">
                      <div id="myTabContent" class="tab-content" style="height: 100%">
                        <div class="panel panel-default hide" id="hide-res-check">0</div>
                        <div class="panel panel-default">
                          <div class="panel-body" id="step_page">
                            <div id="page_body" class="grid-stack" style="display: block;">
                              <div id="main_contents">
                                <input type="hidden" id="current_language" value="ja">
                                <div id="alerts"></div>
                                <div class="container-fluid container-fluid2">
                                  <div class="row row-4">
                                    <div class="col-md-12">
                                      <div class="hide" id="hide_endpoints"></div>
                                      <div id="weko-records">
                                        <div class="col-sm-12">
                                          <div name="metadata" class="form-horizontal">
                                            <!-- react start -->
                                            <div id="input_form_container"></div>
                                            <!-- react end -->
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="main_footer">
      <footer id="footer" style="display: block;">
        <div class="container-fluid">
          <div class="row">
            <div class="col-xs-12">
              <hr>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-12 col-sm-12 text-center-xs">
              <p></p>
              <p>
                <br />
              </p>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </div>
</body>

</html>