app/modules/depositor_admin_setting/depositor_admin_setting/__init__.py
from .ext import AdminSettingApp
__all__ = ('AdminSettingApp')

app/modules/depositor_admin_setting/depositor_admin_setting/views.py
from flask import Flask, render_template, redirect, url_for, request, flash, session ,current_app, jsonify, Blueprint, json
from flask_login import login_user, current_user, logout_user, login_required
from flask_wtf import FlaskForm
from depositor_models.affiliation_id import Affiliation_Id, Affiliation_Id_manager
from depositor_models.affiliation_repository import Affiliation_Repository, Affiliation_Repository_manager
from depositor_login.views import index_login

blueprint = Blueprint(
    "admin_setting",
    __name__,
    url_prefix="/admin_setting",
    template_folder="templates",
    static_folder="static")

@blueprint.route("/", methods=['GET', 'POST'])
def index_affili():
    if not current_user.is_authenticated:
        return redirect(url_for('login.index_login'))
    if request.method == "POST":
        try:
            affiliation_name = request.json.get("affiliation_name")
            repository_url = request.json.get("repository_url")
            access_token = request.json.get("access_token")
            if all([affiliation_name,repository_url,access_token]):
                if current_user.role == "管理者":
                    affiliation_id_info = Affiliation_Id_manager.get_affiliation_id_by_id(affiliation_name)
                else:
                    affiliation_id_info = Affiliation_Id_manager.get_affiliation_id_by_affiliation_name(affiliation_name)
                affiliation_repository_info = Affiliation_Repository_manager.get_aff_repository_by_affiliation_id(affiliation_id_info.id)
                if affiliation_repository_info:
                        aff_repository = {"id":affiliation_repository_info.id,
                                        "affiliation_id":affiliation_id_info.id,
                                        "repository_url":repository_url,
                                        "access_token":access_token}
                        Affiliation_Repository_manager.upt_aff_repository(aff_repository)
                        return jsonify(success=True),200
                else:
                        aff_repository = Affiliation_Repository(affiliation_id=affiliation_id_info.id, repository_url=repository_url, access_token=access_token)
                        Affiliation_Repository_manager.create_aff_repository(aff_repository)
                        return jsonify(success=True),200
            else:
                current_app.logger.error(
                        'ERROR affliation settings: settings is not exist.')
                return jsonify(success=False),400
        except Exception as e:
                current_app.logger.error(
                    'ERROR affliation settings: {}'.format(e))
                return jsonify(success=False),400
    else:
        role = current_user.role
        try:
            if role == "図書館員" or role == "管理者":
                repository_url = ""
                access_token = ""
                if role == "管理者":
                    affiliation_name = "default"
                    affiliation_id_info = Affiliation_Id_manager.get_affiliation_id_by_affiliation_name(affiliation_name)
                    affiliation_repository_info = Affiliation_Repository_manager.get_aff_repository_by_affiliation_id(affiliation_id_info.id)
                else:
                    affiliation_id_info = Affiliation_Id_manager.get_affiliation_id_by_id(current_user.affiliation_id)
                    affiliation_name = affiliation_id_info.affiliation_name
                    affiliation_repository_info = Affiliation_Repository_manager.get_aff_repository_by_affiliation_id(affiliation_id_info.id)
                if affiliation_repository_info:
                    repository_url = affiliation_repository_info.repository_url
                    access_token = affiliation_repository_info.access_token
                affiliation_id_list = Affiliation_Id_manager.get_affiliation_id_list()
                affiliation_repository_list = Affiliation_Repository_manager.get_affiliation_repository_list()
                aff_repository_dict = {}
                for affiliation_repository in affiliation_repository_list:
                    aff_repository_dict[affiliation_repository.affiliation_id] = {"repository_url":affiliation_repository.repository_url, "access_token":affiliation_repository.access_token}
                form = FlaskForm(request.form)
                return render_template("admin_setting/affi_index.html",
                                    form = form,
                                    affiliation_id_list = affiliation_id_list,
                                    aff_repository_dict = json.dumps(aff_repository_dict),
                                    affiliation_name = affiliation_name,
                                    repository_url = repository_url,
                                    access_token = access_token)
            else:
                form = FlaskForm(request.form)
                return render_template("admin_setting/permission_required.html", form = form)
        except Exception as e:
            current_app.logger.error(
               'ERROR affliation settings: {}'.format(e)) 
            return jsonify(success=False),400

@blueprint.route("/add", methods=['GET', 'POST'])
def add_affili():
    if not current_user.is_authenticated:
        return redirect(url_for('login.index_login'))
    if request.method == "POST":
        affiliation_name = request.json.get("affiliation_name")
        affiliation_idp_url = request.json.get("affiliation_idp_url")
        is_affiattion_name = Affiliation_Id_manager.get_affiliation_id_by_affiliation_name(affiliation_name)
        is_affiation_idp_url = Affiliation_Id_manager.get_affiliation_id_by_idp_url(affiliation_idp_url)
        try:
            if not any([is_affiattion_name, is_affiation_idp_url]):
                aff_id = Affiliation_Id(affiliation_idp_url=affiliation_idp_url, affiliation_name=affiliation_name)
                Affiliation_Id_manager.create_affiliation_id(aff_id)
                return jsonify(success=True),200
            else:
                return jsonify(success=False),400
        except Exception as e:
            current_app.logger.error(
                'ERROR affliation settings: {}'.format(e))
            return jsonify(success=False),400
    else:
        if current_user.role == "管理者":
            form = FlaskForm(request.form)
            return render_template("admin_setting/add_affili.html", form = form)
        else:
            form = FlaskForm(request.form)
            return render_template("admin_setting/permission_required.html", form = form)

app/modules/depositor_admin_setting/depositor_admin_setting/templates/admin_setting/_macros.html
{% macro tabs_selector(tab_value='top') %}
{%- if current_user.role == "管理者" %}
<li role="presentation" {% if tab_value=='add' %}class="active"{% endif %}><a href="{{url_for('admin_setting.add_affili')}}">{{ ('登録先追加') }}</a></li>
{%- endif %}
<li role="" {% if tab_value=='setting' %}class="active"{% endif %}><a href="{{url_for('admin_setting.index_affili')}}">{{ ('登録先設定') }}</a></li>
<li role="presentation" {% if tab_value=='item_index' %}class="active"{% endif %}><a href="{{ url_for('item_register.index_item') }}">{{ ('アイテム登録') }}</a></li>
{% endmacro %}

app/modules/depositor_admin_setting/depositor_admin_setting/templates/admin_setting/add_affili.html
{% extends "base.html"  %}

{%- block body %}
{% include "header.html" %}
<div id="main_contents">
  <div class="container-fluid container-fluid2">
    <div class="row row-4">
      <div class="col-sm-12 col-md-12 col-md-12">
        <div class="panel panel-default" id="panel-main-content">
          <div class="panel-heading no-padding-side" id="panel-heading-main-contents">
            <div class="pull-right">
            </div>
            <strong>
              <p id="title-main-content">Overlay</p>
            </strong>
          </div>
            <div class="panel-body panel-body2" id="background-color-main-content">
              <ul class="nav nav-tabs">
                {%- block page_body_tabs %}
                {% from "admin_setting/_macros.html" import tabs_selector with context %}
                {{ tabs_selector('add') }}
                {%- endblock page_body_tabs %}
                  <div class="row row-4" style="height: 100%">
                    <div class="col-sm-12 col-md-12" style="height: 100%">
                      <div id="myTabContent" class="tab-content" style="height: 100%">
                        <div class="panel panel-default hide" id="hide-res-check">0</div>
                        <div class="panel panel-default">
                            <div class="panel-body">
                              <section class="content-header"></section>
                              <div class="row row-4">
                                <div class="row" style="margin-bottom: 15px;">
                                  <div class="col-sm-1 text-right">
                                    <label>機関名</label>
                                  </div>
                                  <div class="col-sm-5">
                                    <input type="text" class="form-control" name="affiliation_name"  id="affiliation_name" required>
                                  </div>
                                </div>
                                <div class="row" style="margin-bottom: 15px;">
                                  <div class="col-sm-1 text-right">
                                    <label>認証機関先URL</label>
                                  </div>
                                  <div class="col-sm-5">
                                    <input type="url" class="form-control" name="affiliation_idp_url" id="affiliation_idp_url" required>
                                  </div>
                                </div>
                                <div class="row row-4">
                                  <div class="col-sm-12 text-center">
                                    <button class="btn btn-primary" id="affili_setting_btn" onclick="handleAddSubmit()">
                                      Save
                                    </button>
                                  </div>
                                </div>
                            </div>
                        </div>
                    </div>
                  </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% include "footer.html" %}
<script type="text/javascript" src="static/js/add_affili.js"></script>
{%- endblock body %}

app/modules/depositor_admin_setting/depositor_admin_setting/templates/admin_setting/affi_index.html
{% extends "base.html"  %}

{%- block body %}
{% include "header.html" %}
<div id="main_contents">
  <div class="container-fluid container-fluid2">
    <div class="row row-4">
      <div class="col-sm-12 col-md-12 col-md-12">
        <div class="panel panel-default" id="panel-main-content">
          <div class="panel-heading no-padding-side" id="panel-heading-main-contents">
            <div class="pull-right">
            </div>
            <strong>
              <p id="title-main-content">Overlay</p>
            </strong>
          </div>
            <div class="panel-body panel-body2" id="background-color-main-content">
              <ul class="nav nav-tabs">
                {%- block page_body_tabs %}
                {% from "admin_setting/_macros.html" import tabs_selector with context %}
                {{ tabs_selector('setting') }}
                {%- endblock page_body_tabs %}
                  <div class="row row-4" style="height: 100%">
                    <div class="col-sm-12 col-md-12" style="height: 100%">
                      <div id="myTabContent" class="tab-content" style="height: 100%">
                        <div class="panel panel-default hide" id="hide-res-check">0</div>
                        <div class="panel panel-default">
                            <div class="panel-body">
                              <section class="content-header"></section>
                              <div class="row row-4">
                                <input type="hidden" id="user_role" value="{{current_user.role}}">
                                <input type="hidden" id="aff_repository_dict" value="{{aff_repository_dict}}">
                                <div class="row" style="margin-bottom: 15px;">
                                  <div class="col-sm-1 text-right">
                                    <label>機関名</label>
                                  </div>
                                  <div class="col-sm-5">
                                    {%- if current_user.role == "図書館員" -%}
                                    <input type="text" class="form-control" name="affiliation_name"  id="affiliation_name"
                                      value={{affiliation_name}} readonly>
                                    {%- endif -%}
                                    {%- if current_user.role == "管理者" -%}
                                    <select class="form-control" name="affiliation_name"  id="affiliation_name" onchange="handleSelect()">
                                      {%- for affiliation_id in affiliation_id_list -%}
                                      <option value="{{affiliation_id.id}}">{{ affiliation_id.affiliation_name }}</option>
                                      {%- endfor -%}
                                    </select>
                                    {%- endif -%}
                                  </div>
                                </div>
                                <div class="row" style="margin-bottom: 15px;">
                                  <div class="col-sm-1 text-right">
                                    <label>登録先URL</label>
                                  </div>
                                  <div class="col-sm-5">
                                    <input type="url" class="form-control" name="repository_url" id="repository_url"
                                    value = {{repository_url}}>
                                  </div>
                                </div>
                                <div class="row" style="margin-bottom: 15px;">
                                  <div class="col-sm-1 text-right">
                                    <label>アクセストークン</label>
                                  </div>
                                  <div class="col-sm-5">
                                    <input type="text" class="form-control" name="access_token" id="access_token" value={{access_token}} >
                                  </div>
                                </div>
                                <div class="row row-4">
                                  <div class="col-sm-12 text-center">
                                    <button class="btn btn-primary" id="affili_save_btn" onclick="handleAffiliSubmit()">
                                      Save
                                    </button>
                                  </div>
                                </div>
                            </div>
                        </div>
                    </div>
                  </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% include "footer.html" %}
<script type="text/javascript" src="static/js/admin_settings.js"></script>
{%- endblock body %}

app/modules/depositor_admin_setting/depositor_admin_setting/templates/admin_setting/permission_required.html
{% extends "base.html" %}

{%- block body %}
{% include "header.html" %}
<div id="main_contents">
  <div class="container-fluid container-fluid2">
    <div class="row row-4">
      <div class="col-sm-12 col-md-12 col-md-12">
        <div class="panel panel-default" id="panel-main-content">
          <div class="panel-heading no-padding-side" id="panel-heading-main-contents">
            <div class="pull-right">
            </div>
            <strong>
              <p id="title-main-content">Overlay</p>
            </strong>
          </div>
          <div class="panel-body panel-body2" id="background-color-main-content">
          </div>
        </div>
      </div>
      <div class="container-fluid">
      <div class="row">
          <div class="col-sm-12 col-md-12 col-lg-10">
          <h1>Permission required</h1>
          <p>You do not have sufficient permissions to view this page.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% include "footer.html" %}
{%- endblock body%}

app/modules/depositor_admin_setting/depositor_admin_setting/templates/base.html
<!DOCTYPE html>
<html lang="en">
<body itemscope="" itemtype="http://schema.org/WebPage" data-spy="scroll" data-target=".scrollspy-target">
    <script type="application/javascript">
      var klaroConfig = {
        version: 2,
        elementID: 'klaro',
        styling: {
          theme: ['dark', 'bottom', 'wide'],
        },
        noAutoLoad: false,
        htmlTexts: true,
        embedded: false,
        groupByPurpose: true,
        storageMethod: 'cookie',
        cookieName: 'klaro',
        cookieExpiresAfterDays: 365,
        default: false,
        mustConsent: false,
        acceptAll: true,
        hideDeclineAll: true,
        hideLearnMore: false,
        noticeAsModal: false,
        poweredBy: 'https://github.com/RCOSDP/weko',
      };
    </script>
    <link rel="stylesheet" href="https://cdn.kiprotect.com/klaro/v0.7.16/klaro.min.css">
    <script type="text/javascript" src="https://cdn.kiprotect.com/klaro/v0.7.16/klaro.js"></script>
    <div id="klaro"
    style="--notice-bottom: 20px; --notice-top: auto; --notice-left: 20px; --notice-right: auto; --notice-max-width: calc(100vw - 60px); --notice-position: fixed;">
    <div lang="ja" class="klaro">
    </div>
    </div>


    {% block css %}
    <link href={{url_for('static', filename='css/theme.css' )}} rel="stylesheet">
    <link href={{url_for('static', filename='css/styles.css' )}} rel="stylesheet">
    <link href={{url_for('static', filename='css/buttons.css' )}} rel="stylesheet">
    <link href={{url_for('static', filename='css/admin.css' )}} rel="stylesheet">
    {% endblock %}
    {%- block body %}

    {%- endblock body %}
</body>

</html>

app/modules/depositor_admin_setting/depositor_admin_setting/templates/footer.html
<div id="main_footer">
    <footer id="footer" style="display: block;">
        <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12">
            <hr>
            </div>
        </div>
        </div>
    </footer>
</div>

app/modules/depositor_admin_setting/depositor_admin_setting/templates/header.html
<div id="header">
    <nav class="navbar-default navbar-static-top full-height">
    <div class="container-fluid container-fluid2" id="fixed_header">
        <div class="navbar-header">
        </div>
        <ul class="nav navbar-nav">
        </ul>
        <div class="navbar-form navbar-right navbar-form2">
        <div class="btn-group">
            <a class="btn btn-default btn-primary bg-transparent">
            <input id="current_user_email" type="hidden" value="{{current_user.user_id}}">
            {{current_user.user_id}}
            </a>
            <a class="btn btn-default btn-primary bg-transparent" href="{{ url_for('login.logout') }}"> ログアウト</a>
        </div>
        </div>
        <div class="navbar-form navbar-right navbar-form2">
        </div>
        <!--     <input hidden id ="weko_show_index_for_authenticated_user" value="False"> -->
    </div>
    </nav>
</div>